<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dog</string>
	</array>
	<key>name</key>
	<string>Dog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.dog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.dog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.dog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords that delimit flow blocks or alter flow from within a block</string>
			<key>match</key>
			<string>(?i)\b(if|else|while|with|break|continue|pass|return|listen|on|each|do|end|wait|sequentially)\b</string>
			<key>name</key>
			<string>keyword.control.flow.dog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords that haven't fit into other groups (yet).</string>
			<key>match</key>
			<string>(?i)\b(in|of|for|as|assert|delete|print|notify|ask|compute|define|to|via|using|from|add|where|and|or|perform|all)\b</string>
			<key>name</key>
			<string>keyword.other.dog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.dog</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.dog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>double-quoted string</string>
			<key>end</key>
			<string>((?&lt;=")(")|")|(\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.dog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.empty-string.double.dog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unclosed-string.dog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.single-line.dog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language Variables</string>
			<key>match</key>
			<string>'.*'</string>
			<key>name</key>
			<string>string.quoted.single.single-line.dog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language Variables</string>
			<key>match</key>
			<string>(?i)\b(public|people|person|http|email|sms|stream)\b</string>
			<key>name</key>
			<string>variable.language.dog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dog</string>
	<key>uuid</key>
	<string>1C3E6794-F3C0-4467-8F15-A59810923D46</string>
</dict>
</plist>
